services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - user_data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  user_data: