# fly.toml app configuration file generated for eateries-essentials on 2025-09-12T01:46:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eateries-essentials'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = 'eateries_data'
  destination = '/app/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
